#!/bin/bash
# Neo-Hack: Gridlock - Promo Video Generator
# This script converts the WebP recording generated by the browser agent into a YouTube-ready MP4.

if [ "$#" -ne 1 ]; then
    echo "Usage: ./generate_promo.sh <input_recording.webp>"
    echo "Example: ./generate_promo.sh /home/kalxav/.gemini/antigravity/brain/.../cyberwar_promo.webp"
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="neo_hack_promo_trailer.mp4"

echo "=================================================="
echo " NEO-HACK: GRIDLOCK - PROMO GENERATOR TOOL"
echo "=================================================="
echo "Target Input: $INPUT_FILE"
echo "Target Output: $OUTPUT_FILE"

if ! command -v ffmpeg &> /dev/null; then
    echo "[!] Error: ffmpeg is not installed."
    echo "    Please install it using: sudo apt install ffmpeg"
    exit 1
fi

if [ ! -f "$INPUT_FILE" ]; then
    echo "[!] Error: Input file not found."
    exit 1
fi

echo "[*] Converting WebP recording to high-quality MP4 (H.264)..."
echo "[*] This may take a few moments depending on the simulation length."

# FFmpeg command to convert animated webp to mp4 suitable for YouTube
ffmpeg -i "$INPUT_FILE" -vcodec libx264 -pix_fmt yuv420p -crf 20 -preset slow "$OUTPUT_FILE" -y

if [ $? -eq 0 ]; then
    echo "[+] SUCCESS! Video generated at: $OUTPUT_FILE"
    echo "[+] You can now upload this file directly to YouTube."
else
    echo "[-] FAILED to generate video."
    exit 1
fi
