"""Add world state and epoch models

Revision ID: 6f78e6e6c1b6
Revises: 
Create Date: 2026-03-15 13:55:19.366583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f78e6e6c1b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epoch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('PLANNING', 'SIM', 'TRANSITION', name='epochphase'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epoch_number'), 'epoch', ['number'], unique=True)
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('compute_reserves', sa.Integer(), nullable=False),
    sa.Column('global_influence_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faction_name'), 'faction', ['name'], unique=True)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('defense_level', sa.Integer(), nullable=False),
    sa.Column('compute_output', sa.Integer(), nullable=False),
    sa.Column('node_class', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='nodeclass'), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=True)
    op.create_table('epochaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epoch_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('SCAN', 'BREACH', 'DEFEND', 'TREATY', name='actiontype'), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('cu_committed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epoch_id'], ['epoch.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epochaction')
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.drop_table('player')
    op.drop_table('node')
    op.drop_index(op.f('ix_faction_name'), table_name='faction')
    op.drop_table('faction')
    op.drop_index(op.f('ix_epoch_number'), table_name='epoch')
    op.drop_table('epoch')
    # ### end Alembic commands ###
