"""Add Accord and NewsItem tables for Sprint 3 Diplomacy

Revision ID: 85e1535690f3
Revises: 6f78e6e6c1b6
Create Date: 2026-03-15 13:30:55.354069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e1535690f3'
down_revision: Union[str, Sequence[str], None] = '6f78e6e6c1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
